# Generated by Django 2.0.3 on 2018-04-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
