# Generated by Django 2.0.3 on 2018-05-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laf_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('kind', models.CharField(choices=[('lost', '失物招领'), ('found', '寻物启事')], default='失物招领', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=None, to='login.User')),
            ],
            options={
                'verbose_name': '失物招领及寻物启事信息',
                'verbose_name_plural': '失物招领及寻物启事信息',
                'ordering': ['-c_time'],
            },
        ),
    ]
