# Generated by Django 2.0.3 on 2018-05-24 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laf_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laf_info',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
    ]
