# Generated by Django 2.0.3 on 2018-05-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laf_info', '0003_laf_info_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='laf_info',
            name='doc_info',
            field=models.TextField(default='无'),
        ),
    ]
