# Generated by Django 2.0.3 on 2018-06-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laf_info', '0004_laf_info_doc_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='laf_info',
            name='tkind',
            field=models.CharField(choices=[('1', '证件类型'), ('0', '非证件类型')], default='非证件类型', max_length=32),
        ),
    ]
