# Generated by Django 2.0.3 on 2018-06-18 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laf_info', '0005_laf_info_tkind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laf_info',
            name='tkind',
        ),
    ]
